apiVersion: v1
kind: Secret
metadata:
  name: auto-private-link-azure-sp
type: Opaque
data:
  armAuth.json: "{{- required "armAuth.secretJSON is required when using servicePrincipal" .Values.armAuth.secretJSON -}}"
