apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "auto-private-link.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "auto-private-link.serviceaccountname" . }}